language: node_js
node_js:
  - '10'
env:
  - CODECOV_TOKEN="b1916671-a54f-451d-aad8-6324be40418a" VUE_APP_API_URL="https://api.test.camino.beta.gouv.fr" CYPRESS_apiUrl="https://api.test.camino.beta.gouv.fr" CYPRESS_userEmail="test@camino.beta.gouv.fr" CYPRESS_userPassword="fake-secret-password-for-cypress"
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - '~/.cache'
