version: '3'

services:
  app:
    container_name: camino_ui_app
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      PORT: ${PORT}
      VITE_API_URL: ${VITE_API_URL}
      API_MATOMO_URL: ${API_MATOMO_URL}
      API_MATOMO_ID: ${API_MATOMO_ID}
      API_SENTRY_URL: ${API_SENTRY_URL}
    expose:
      - ${PORT}
    networks:
      - default
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true
