version: '3'

services:
  app:
    container_name: camino_ui_app
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      API_URL: ${API_URL}
      PORT: ${PORT}
      API_MATOMO_URL: ${API_MATOMO_URL}
      API_MATOMO_ID: ${API_MATOMO_ID}
    networks:
      - default
      - nginx-proxy
    expose:
      - ${PORT}

networks:
  nginx-proxy:
    external: true
