version: '3'

services:
  app:
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
    expose:
      - ${NODE_PORT}
    volumes:
      - ./.env:/app/.env

networks:
  default:
    external:
      name: nginx-proxy
