version: '3'

services:
  app:
    container_name: camino_ui_app
    build: .
    environment:
      PORT: ${PORT}
      API_URL: ${API_URL}
      API_MATOMO_URL: ${API_MATOMO_URL}
      API_MATOMO_ID: ${API_MATOMO_ID}
      ENV: ${ENV}
    ports:
    - ${PORT}:${PORT}

