version: '3'

services:
  app:
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
      API_URL: ${API_URL}
      NODE_PORT: ${NODE_PORT}
      API_MATOMO_URL: ${API_MATOMO_URL}
      API_MATOMO_ID: ${API_MATOMO_ID}
      API_SENTRY_URL: ${API_SENTRY_URL}
    networks:
      - default
      - nginx-proxy
    expose:
      - ${NODE_PORT}

networks:
  nginx-proxy:
    external: true
