"Titre minier"
type Titre {
  """
  L'__id__ du titre est constituée de la concaténation:
  - du type en 3 lettres.
  - du nom du titre en minuscule, sans caractères spéciaux, avec des tirets au lieu des espaces.

  Exemples: _con-saint-elie_ ou _per-pedral_.
  """
  id: ID!
  nom: String!
  type: Type!
  domaine: Domaine!
  statut: Statut!
  police: Boolean!
  substancesPrincipales: [Substance]
  substancesSecondaires: [Substance]
  references: [Reference]
  phases: [Phase]
}

type Type {
  id: TypeId!
  nom: String!
}

type Domaine {
  id: DomaineId!
  nom: String!
}

type Statut {
  id: StatutId!
  nom: String!
}

type Reference {
  type: String
  nom: String!
}

type Phase {
  id: ID!
  type: PhaseType!
  duree: Int!
  date: String!
  emprise: [Emprise]
  geojsonMultiPolygon: GeojsonMultiPolygon
  geojsonPoints: GeojsonPoints
}

type PhaseType {
  id: ID!
  nom: String!
  dureeMax: Int!
  renouvelable: Boolean
  exception: Boolean
}

type Emprise {
  id: EmpriseId!
  nom: String!
}

"tauuust"
input InputTitre {
  """
  L'__id__ du titre est constituée de la concaténation:
  - du type en 3 lettres.
  - du nom du titre en minuscule, sans caractères spéciaux, avec des tirets au lieu des espaces.

  Exemples: _con-saint-elie_ ou _per-pedral_.
  """
  id: ID!
  nom: String!
  type: InputType!
  domaine: InputDomaine!
  statut: InputStatut!
  police: Boolean!
  substancesPrincipales: [InputSubstanceId!]
  substancesSecondaires: [InputSubstanceId!]
  references: [InputReference]
  phases: [InputPhases]
}

input InputType {
  id: TypeId!
}

input InputDomaine {
  id: DomaineId!
}

input InputStatut {
  id: StatutId!
}

input InputSubstanceId {
  id: ID!
}

input InputReference {
  type: String
}

input InputPhases {
  id: ID!
  type: InputPhaseType!
  duree: Int!
  date: String!
  emprise: [InputEmprise]
}

input InputPhaseType {
  id: ID!
  nom: String
  dureeMax: Int
  renouvelable: Boolean
  exception: Boolean
}

input InputEmprise {
  id: EmpriseId!
  nom: String
}

"""
- __apx__: Autorisation de prospections préalables (M, H, C)
- __arc__: Autorisation de recherches (C)
- __arg__: Autorisation de recherches (G)
- __axm__: Autorisation d'exploitation (M)
- __prx__: Permis exclusif de recherches (M, G, S, C)
- __prh__: Permis exclusif de recherches (H)
- __pxc__: Permis exclusif de carrières (C)
- __pxg__: Permis d'exploitation (G)
- __pxm__: Permis d'exploitation (M)
- __cxx__: Concession (M, H, G, S, C)
"""
enum TypeId {
  apx
  arc
  arg
  axm
  prx
  prh
  pxc
  pxg
  pxm
  cxx
}

"""
- __m__: Minéraux et métaux
- __h__: Substances énergétiques
- __s__: Stockage
- __g__: Géothermie
- __c__: Carrières et granulats marins
"""
enum DomaineId {
  m
  h
  s
  g
  c
}

"""
- __ins__: En instruction
- __val__: Valide
- __ech__: Échu
"""
enum StatutId {
  dmi
  dmc
  val
  mdi
  ech
}

"""
- __ter__: À terre
- __mer__: En mer
"""
enum EmpriseId {
  ter
  mer
}
