name: CI
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test units
        run: |
          npm ci
          npm test
        env:
          CODECOV_TOKEN: 'b1916671-a54f-451d-aad8-6324be40418a'
          CI: true

  build:
    if: github.ref == 'refs/heads/develop' || github.event_name == 'release'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build . --tag caminofr/camino-ui:develop
      - name: Push Docker image to the Docker Hub
        run: |
          docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
          docker push caminofr/camino-ui:develop
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   - name: Install SSH key
    #     with:
    # key: ${{ secrets.SSH_KEY }}
    # known_hosts: ${{ secrets.KNOWN_HOSTS }}
    # config: |
    #   Host github
    #     Hostname github.com
    #     User git
    #     IdentityFile ~/.ssh/ssh_key_name
    #   - name: Redeploy dev
    #     run : |
    #       ssh dev
    #       /srv/script/api-deploy

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15]

    steps:
      - name: Add the release tag
        run: |
          docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
          docker pull caminofr/camino-ui:develop
          docker tag caminofr/camino-ui:develop caminofr/camino-ui:$VERSION
          docker push caminofr/camino-ui:$VERSION
          docker tag caminofr/camino-ui:develop caminofr/camino-ui:latest
          docker push caminofr/camino-ui:latest
          docker tag caminofr/camino-ui:develop caminofr/camino-ui:master
          docker push caminofr/camino-ui:master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{ github.event.release.tag_name }}
